apiVersion: cilium.io/v2alpha1
kind: CiliumGatewayClassConfig
metadata:
  name: kube-vip
  namespace: cilium
spec:
  service:
    type: LoadBalancer
    loadBalancerClass: "kube-vip.io/kube-vip-class"
    allocateLoadBalancerNodePorts: false
    externalTrafficPolicy: Cluster
    ipFamilies:
      - IPv4
    ipFamilyPolicy: SingleStack
